border=no
keep-open=yes

osc=no
osd-bar=no

vo=opengl-hq:interpolation:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:tscale=oversample:scaler-resizes-only:dither-depth=8:temporal-dither:pbo:target-prim=bt.709:target-trc=bt.1886:deband:blend-subtitles=yes
gpu-hq

screenshot-format=jpg
screenshot-tag-colorspace=yes
screenshot-template="%F_%p_%n"
screenshot-directory=~/anime_screenshots
