##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    name = supress_maximize
    suppress_event = maximize
    match:class = .*
}

windowrule {
    name = discordWorkspace
    match:class = discord.*
    workspace = 2
    no_initial_focus = on
}

windowrule {
    name = umamusumeFloat
    match:class = steam_app_3224770
    float = on
}

# Fix some dragging issues with XWayland
windowrule {
    name = xwaylandDrag
    no_focus = on
    match:class = ^$,
    match:title = ^$,
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
}
